version: '3'
services:
  db:
    container_name: gosqldb
    image: mysql:8.1.0
    ports:
      - ${database_port}:${database_port}
    environment:
      - MYSQL_ROOT_PASSWORD=${database_password}
      - MYSQL_DATABASE=chating
    networks:
      - ctnetwork 
  gin:
    container_name: chatroom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${server_port}:${server_port}"
    volumes:
      - .:/chatroom
    depends_on:
      - db
    networks:
      - ctnetwork 
    command: bash -c "dockerize -wait tcp://gosqldb:${database_port} -timeout 300s -wait-retry-interval 5s && go run main.go"
networks:
  ctnetwork: