version: '3'
services:
  db:
    container_name: gosqldb
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=chating
    networks:
      - ctnetwork 
  gin:
    container_name: chatroom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/chatroom
    depends_on:
      - db
    networks:
      - ctnetwork 
    command: bash -c "dockerize -wait tcp://gosqldb:3306 -timeout 300s -wait-retry-interval 5s && go run main.go"
networks:
  ctnetwork: